/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 truck.glb --transform --shadows 
Files: truck.glb [170.7KB] > /Users/daniyal.farooque/Documents/JSProject/Mario-Kart-3.js/public/models/misc/truck-transformed.glb [21.69KB] (87%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
export function Truck(props) {
  
  const { nodes, materials } = useGLTF('./models/misc/truck-transformed.glb')
  console.log("this is items truck")
  return (
    <group {...props} dispose={null} scale={[100,100,100]} >
      <mesh castShadow receiveShadow geometry={nodes.MM_Camion_ParteDelantera.geometry} material={materials.mobile_Camion} position={[0.187, 0.047, 0.052]} rotation={[Math.PI / 2, 0, -1.616]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.MM_Camion_CristalParabrisas.geometry} material={materials.MM_Camion1} position={[0.199, 0.062, 0.052]} rotation={[Math.PI / 2, 0, -1.616]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.MM_Camion_RuedaDelantera01.geometry} material={materials.Material} position={[0.205, 0.044, 0.042]} rotation={[Math.PI / 2, 0, -1.616]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.MM_Camion_ParteTrasera.geometry} material={materials.mobile_Camion_trans} position={[0.188, 0.047, 0.052]} rotation={[Math.PI / 2, 0, -1.616]} scale={0.01} />
    </group>
  )

}

useGLTF.preload('./models/misc/truck-transformed.glb')
